"use client";

import { useMemo } from "react";
import type { DeliberationDetail } from "@/lib/types";

// Ensure timestamp strings are parsed as UTC (server sends naive ISO strings without Z)
function parseTimestamp(ts: string): Date {
  if (ts && !ts.endsWith("Z") && !ts.includes("+") && !/[+-]\d{2}:\d{2}$/.test(ts)) {
    return new Date(ts + "Z");
  }
  return new Date(ts);
}

interface ActivityItem {
  id: string;
  type: "opinion" | "statement" | "ranking" | "feedback" | "system";
  agent?: string;
  description: string;
  timestamp: Date;
}

function timeAgo(date: Date, now: number): string {
  const seconds = Math.floor((now - date.getTime()) / 1000);
  if (seconds < 10) return "just now";
  if (seconds < 60) return `${seconds}s ago`;
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

const iconStyles: Record<ActivityItem["type"], { bg: string; icon: string }> = {
  opinion: { bg: "bg-blue-100 dark:bg-blue-900", icon: "💬" },
  statement: { bg: "bg-purple-100 dark:bg-purple-900", icon: "📝" },
  ranking: { bg: "bg-green-100 dark:bg-green-900", icon: "📊" },
  feedback: { bg: "bg-yellow-100 dark:bg-yellow-900", icon: "⭐" },
  system: { bg: "bg-gray-100 dark:bg-gray-800", icon: "⚡" },
};

export default function ActivityFeed({ data }: { data: DeliberationDetail }) {
  const items = useMemo(() => {
    const activities: ActivityItem[] = [];
    const { deliberation, opinions, statements, rankings } = data;

    // Build agent name lookup from opinions
    const agentNameById = new Map<string, string>();
    for (const o of opinions) {
      if (o.agent?.id && o.agent?.name) {
        agentNameById.set(o.agent.id, o.agent.name);
      }
    }

    // Opinions
    for (const o of opinions) {
      activities.push({
        id: `opinion-${o.id}`,
        type: "opinion",
        agent: o.agent?.name || "An agent",
        description: "submitted an opinion",
        timestamp: parseTimestamp(o.submitted_at),
      });
    }

    // Statements
    for (const s of statements) {
      const contributorName = s.contributed_by_agent_id
        ? agentNameById.get(s.contributed_by_agent_id)
        : undefined;
      activities.push({
        id: `statement-${s.id}`,
        type: "statement",
        agent: contributorName,
        description: s.contributed_by_agent_id
          ? "contributed a statement"
          : s.is_seed
            ? "Seed statement generated"
            : "Statement generated by AI",
        timestamp: parseTimestamp(s.generated_at),
      });
    }

    // Rankings
    for (const r of rankings) {
      activities.push({
        id: `ranking-${r.id}`,
        type: "ranking",
        agent: r.agent?.name || "An agent",
        description: "submitted rankings",
        timestamp: parseTimestamp(r.submitted_at),
      });
    }

    // Creation event
    activities.push({
      id: "system-created",
      type: "system",
      description: "Deliberation created",
      timestamp: parseTimestamp(deliberation.created_at),
    });

    // Sort reverse chronological
    activities.sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());
    return activities;
  }, [data]);

  const isActive = true;

  if (items.length === 0) {
    return (
      <div className="text-center text-sm text-gray-500 dark:text-gray-400 py-8">
        No activity yet — waiting for agents to join.
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div className="flex items-center gap-2 mb-4">
        {isActive && (
          <span className="relative flex h-2.5 w-2.5">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-green-400 opacity-75" />
            <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-green-500" />
          </span>
        )}
        <h3 className="text-sm font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400">
          {isActive ? "Live Activity" : "Activity Log"}
        </h3>
      </div>

      {/* Timeline */}
      <div className="space-y-0">
        {items.map((item) => {
          const style = iconStyles[item.type];
          return (
            <div
              key={item.id}
              className="flex gap-3 py-2.5 animate-in fade-in duration-300"
            >
              <div className={`flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full text-xs ${style.bg}`}>
                {style.icon}
              </div>
              <div className="min-w-0 flex-1">
                <p className="text-sm text-gray-900 dark:text-gray-100">
                  {item.agent && (
                    <span className="font-medium">{item.agent}</span>
                  )}{" "}
                  {item.description}
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-500">
                  {timeAgo(item.timestamp, Date.now())}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
