"""
Service for generating candidate consensus statements using multiple LLMs.

Replaces the statement generation part of the Habermas Machine.
Each candidate statement is generated by a (potentially different) model,
enabling cross-model evaluation and leaderboard ranking.
"""

import asyncio
import itertools
import logging
import random
import re
from typing import List, Optional, Tuple

from sqlalchemy.orm import Session

from app.config import settings
from app.models import Deliberation, Statement
from app.services.llm_client import LLMClient

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System prompt (shared across all statement generation calls)
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a neutral mediator helping a group reach consensus on a question.
Your job is to draft a concise group statement that captures shared views
without contradicting any individual opinion.

Always respond in exactly this format:

REASONING:
<your analysis of the opinions, noting agreement and disagreement>

TITLE:
<a short title of 5-10 words that captures the essence of the statement>

STATEMENT:
<the consensus statement, 1-3 sentences>\
"""

# ---------------------------------------------------------------------------
# User prompts
# ---------------------------------------------------------------------------


def _build_opinion_only_prompt(
    question: str,
    opinions: list[str],
) -> str:
    """User prompt for the initial round (opinions only)."""
    lines = [f"Question: {question}", "", "Individual opinions:"]
    for i, opinion in enumerate(opinions):
        lines.append(f"  Person {i + 1}: {opinion}")
    lines.append("")
    lines.append(
        "Analyze the opinions above, then write a consensus statement "
        "that reflects the group's shared perspective without contradicting "
        "any individual opinion."
    )
    return "\n".join(lines)


def _build_opinion_critique_prompt(
    question: str,
    opinions: list[str],
    previous_winner: str,
    critiques: list[str],
) -> str:
    """User prompt for critique rounds (opinions + previous statement + critiques)."""
    lines = [f"Question: {question}", "", "Individual opinions:"]
    for i, opinion in enumerate(opinions):
        lines.append(f"  Person {i + 1}: {opinion}")
    lines.append(f"\nPrevious draft statement: {previous_winner}")
    lines.append("\nCritiques of the draft:")
    for i, critique in enumerate(critiques):
        lines.append(f"  Person {i + 1}: {critique}")
    lines.append("")
    lines.append(
        "Using the opinions and critiques above, write a revised consensus "
        "statement that addresses the feedback while still reflecting the "
        "group's shared perspective."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Response parsing
# ---------------------------------------------------------------------------

_STATEMENT_RE = re.compile(
    r"REASONING:\s*(.+?)\s*TITLE:\s*(.+?)\s*STATEMENT:\s*(.+)",
    re.DOTALL,
)

# Fallback for responses without TITLE field (backward compat)
_STATEMENT_RE_NO_TITLE = re.compile(
    r"REASONING:\s*(.+?)\s*STATEMENT:\s*(.+)",
    re.DOTALL,
)


def _parse_response(response: str) -> Tuple[str, str, str]:
    """Extract statement, title, and reasoning from the model response.

    Returns:
        (statement, title, reasoning). Falls back to ("", "", "PARSE_FAILED") on failure.
    """
    match = _STATEMENT_RE.search(response)
    if match:
        reasoning = match.group(1).strip()
        title = match.group(2).strip()
        statement = match.group(3).strip()
        return statement, title, reasoning
    # Fallback: no TITLE section
    match = _STATEMENT_RE_NO_TITLE.search(response)
    if match:
        reasoning = match.group(1).strip()
        statement = match.group(2).strip()
        return statement, "", reasoning
    return "", "", "PARSE_FAILED"


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class StatementService:
    """Generates candidate group statements using multiple LLM models."""

    def __init__(self):
        self.num_candidates = settings.HABERMAS_NUM_CANDIDATES
        self.num_retries = settings.HABERMAS_NUM_RETRIES
        model_list = settings.habermas_model_list
        # One LLMClient per unique model, keyed by name
        self.clients = {name: LLMClient(model_name=name) for name in model_list}
        # Build the per-candidate model assignment by cycling through the list
        self.candidate_models = [
            m for m, _ in zip(itertools.cycle(model_list), range(self.num_candidates))
        ]

    def _generate_single_statement(
        self,
        client: LLMClient,
        question: str,
        opinions: list[str],
        previous_winner: Optional[str] = None,
        critiques: Optional[list[str]] = None,
    ) -> Tuple[str, str, str]:
        """Generate one candidate statement with retries. Returns (statement, title, reasoning)."""
        # Shuffle opinions (and critiques) to avoid ordering bias
        indices = list(range(len(opinions)))
        random.shuffle(indices)
        shuffled_opinions = [opinions[i] for i in indices]
        shuffled_critiques = [critiques[i] for i in indices] if critiques else None

        if previous_winner and shuffled_critiques:
            user_prompt = _build_opinion_critique_prompt(
                question, shuffled_opinions, previous_winner, shuffled_critiques
            )
        else:
            user_prompt = _build_opinion_only_prompt(question, shuffled_opinions)

        seed = random.randint(0, 2**31 - 1)

        statement, title, reasoning = "", "", ""
        for attempt in range(self.num_retries):
            response = client.sample_text(
                user_prompt, system_prompt=SYSTEM_PROMPT, seed=seed
            )
            statement, title, reasoning = _parse_response(response)
            if len(statement) > 5 and reasoning != "PARSE_FAILED":
                return statement, title, reasoning
            seed += 1
            logger.warning(
                f"Statement generation attempt {attempt + 1}/{self.num_retries} "
                f"failed (model={client._model_name}): {reasoning[:100]}"
            )

        return statement, title, reasoning

    async def generate_statements(
        self,
        db: Session,
        deliberation: Deliberation,
        opinions: list[str],
        round_number: int,
        previous_winner: Optional[str] = None,
        critiques: Optional[list[str]] = None,
    ) -> List[Statement]:
        """
        Generate num_candidates statements and store them in the database.

        Each candidate is assigned a model from the configured model list (cycled
        if there are fewer models than candidates).

        Returns list of Statement model instances.
        """
        async def _generate_one(i: int, model_name: str):
            client = self.clients[model_name]
            logger.info(
                f"Generating statement {i + 1}/{self.num_candidates} "
                f"(model={model_name}) for deliberation {deliberation.id}"
            )
            stmt, title, reasoning = await asyncio.to_thread(
                self._generate_single_statement,
                client, deliberation.question, opinions, previous_winner, critiques,
            )
            return (stmt, title, reasoning, model_name)

        # Run all LLM calls concurrently
        results = await asyncio.gather(
            *[_generate_one(i, m) for i, m in enumerate(self.candidate_models)]
        )

        # Store in database — social_ranking is NULL at this point
        statements = []
        for stmt_text, title, reasoning, model_name in results:
            if stmt_text:  # Skip empty statements from failed generations
                statement = Statement(
                    deliberation_id=deliberation.id,
                    round_number=round_number,
                    title=title or None,
                    statement_text=stmt_text,
                    social_ranking=None,
                    meta_data={"reasoning": reasoning, "model": model_name},
                )
                db.add(statement)
                statements.append(statement)

        db.commit()

        logger.info(
            f"Generated {len(statements)} statements for deliberation "
            f"{deliberation.id} round {round_number}"
        )
        return statements


# Global service instance
statement_service = StatementService()
