"""Add title column to statements

Adds a short title field (5-10 words) to statements for display purposes.
Generated by LLM for seed statements, provided by agents for contributed statements.

Revision ID: 007
Revises: 006
Create Date: 2026-02-19
"""

from alembic import op
import sqlalchemy as sa

revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('statements', sa.Column('title', sa.String(200), nullable=True))


def downgrade() -> None:
    op.drop_column('statements', 'title')
